In [3]:
import numpy as np
import tensorflow as tf

1.4 Selecting Elements

In [6]:
# Load library
import numpy as np
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])



In [4]:
# Select third element of vector
vector[2]

3

In [5]:
# Select second row, second column
matrix[1,1]

5

In [11]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [12]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [13]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [ ]:
# Select the last element
vector[-1]

6

In [7]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

1.5 Describing a Matrix

In [9]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]])

In [10]:
# View number of rows and columns
matrix.shape

(3, 4)

In [11]:
# View number of elements (rows * columns)
matrix.size

12

In [12]:
# View number of dimensions
matrix.ndim

2

1.6 Applying Operations to Elements

In [13]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Create function that adds 100 to something
add_100 = lambda i: i + 100
# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)
# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [14]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

1.7 Finding the Maximum and Minimum Values

In [15]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Return maximum element
np.max(matrix)

9

In [16]:
# Return minimum element
np.min(matrix)

1

In [17]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [18]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

1.8 Calculating the Average, Variance, and Standard
Deviation

In [19]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [20]:
# Return mean
np.mean(matrix)

5.0

In [21]:
# Return variance
np.var(matrix)

6.666666666666667

In [22]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [23]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

1.9 Reshaping Arrays

In [24]:
# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9],
 [10, 11, 12]])

In [25]:
# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [26]:
matrix.size

12

In [27]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [28]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1.10 Transposing a Vector or Matrix

In [29]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [31]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

1.11 Flattening a Matrix

In [32]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

1.13 Calculating the Determinant

In [34]:
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return determinant of matrix
np.linalg.det(matrix)

0.0

1.14 Getting the Diagonal of a Matrix

In [35]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return diagonal elements
matrix.diagonal()


array([1, 4, 9])

In [36]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [37]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

1.15 Calculating the Trace of a Matrix

In [38]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
 [2, 4, 6],
 [3, 8, 9]])
# Return trace
matrix.trace()

14

In [39]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

1.16 Finding Eigenvalues and Eigenvectors

In [40]:
# Load library
import numpy as np
# Create matrix
matrix = np.array([[1, -1, 3],
 [1, 1, 6],
 [3, 8, 9]])
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
# View eigenvalues
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [41]:
# View eigenvectors
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

1.17 Calculating Dot Products

In [42]:
# Load library
import numpy as np
# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])
# Calculate dot product
np.dot(vector_a, vector_b)

32

In [43]:
# Calculate dot product
vector_a @ vector_b

32

1.18 Adding and Subtracting Matrices

In [44]:
# Create matrix
matrix_a = np.array([[1, 1, 1],
 [1, 1, 1],
 [1, 1, 2]])
# Create matrix
matrix_b = np.array([[1, 3, 1],
 [1, 3, 1],
 [1, 3, 8]])
# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [45]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [46]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

1.19 Multiplying Matrices

In [47]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([[1, 1],
 [1, 2]])
# Create matrix
matrix_b = np.array([[1, 3],
 [1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [48]:
# Multiply two matrices
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])